"use client";

import { BadgeCheck, Clock3, MoreHorizontal, TrendingUp, Wallet } from "lucide-react";
import { CartesianGrid, Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { useSession } from "next-auth/react";
import ProgressMetricCard, { type SeriesPoint } from "@/components/ui/progress-metric-card";
import { useRequests } from "@/lib/queries/requests";
import { volumeSeries } from "@/lib/mock-data";

const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const summaryCards = [
  { title: "Pending requests", key: "pending", icon: Clock3, color: "text-amber-700 bg-amber-500/10", trend: "Needs review" },
  { title: "Approval rate", key: "approval", icon: BadgeCheck, color: "text-emerald-700 bg-emerald-500/10", trend: "+2.4%" },
];

export function DashboardOverview() {
  const { data: session } = useSession();
  const { data = [], isLoading } = useRequests();
  const deposits = data.filter((row) => row.kind === "deposit");
  const withdrawals = data.filter((row) => row.kind === "withdrawal");
  const pending = data.filter((row) => row.status === "pending");
  const decided = data.filter((row) => row.status !== "pending");
  const usdRates: Record<string, number> = { USD: 1, EUR: 1.08, GBP: 1.27, AED: 0.27 };
  const toUsd = (amount: number, code: string) => amount * (usdRates[code] ?? 1);
  const values: Record<string, string | number> = {
    deposit: currency(deposits.reduce((total, row) => total + toUsd(row.amount, row.currency), 0)),
    withdrawal: currency(withdrawals.reduce((total, row) => total + toUsd(row.amount, row.currency), 0)),
    pending: pending.length,
    approval: `${decided.length ? Math.round((decided.filter((row) => row.status === "approved").length / decided.length) * 100) : 0}%`,
  };
  const recent = [...data].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,5);
  const pendingStop = data.length ? pending.length / data.length * 100 : 0;
  const approvedStop = data.length ? data.filter((row) => row.status === "approved").length / data.length * 100 + pendingStop : pendingStop;
  const depositSeries: SeriesPoint[] = volumeSeries.map((point) => ({ date: point.date, value: point.deposits * 1000 }));
  const withdrawalSeries: SeriesPoint[] = volumeSeries.map((point) => ({ date: point.date, value: point.withdrawals * 1000 }));
  const compactUsd = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(value);
  return <div className="mx-auto max-w-[1440px] space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Payment operations · Daily overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Good morning, {session?.user.name?.split(" ")[0] ?? "there"} <span aria-hidden>✦</span></h1><p className="mt-2 text-sm text-muted-foreground">Here’s what’s happening across your payment operations.</p></div><div className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-emerald-500" />Last synced 2 minutes ago</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 xl:items-stretch">
      <ProgressMetricCard title="Total deposits" total={String(values.deposit)} delta="+$8.4K" percent="12.8%" trend="up" unit="USD" data={depositSeries} valueFormatter={compactUsd} dateFormatter={(date) => date} size="sm" className="ib-portal-metric xl:col-span-2" />
      <ProgressMetricCard title="Total withdrawals" total={String(values.withdrawal)} delta="+$3.1K" percent="8.2%" trend="up" unit="USD" data={withdrawalSeries} valueFormatter={compactUsd} dateFormatter={(date) => date} size="sm" className="ib-portal-metric xl:col-span-2" />
      {summaryCards.map(({ title, key, icon: Icon, color, trend }) => <article key={key} className="ib-portal-metric flex min-h-[260px] flex-col justify-between rounded-[28px] bg-card p-5"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${color}`}><Icon className="size-5" /></span><button className="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-muted" aria-label={`${title} menu`}><MoreHorizontal className="size-4" /></button></div><div><p className="text-sm text-muted-foreground">{title}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{isLoading ? "—" : values[key]}</p><p className="mt-3 flex items-center gap-1.5 text-xs"><span className={`inline-flex items-center gap-1 font-medium ${key === "pending" ? "text-amber-700 dark:text-amber-300" : "text-emerald-700 dark:text-emerald-300"}`}><TrendingUp className="size-3.5" />{trend}</span><span className="text-muted-foreground">vs last month</span></p></div></article>)}
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.65fr_0.85fr]">
      <section className="ib-portal-metric rounded-2xl bg-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><Wallet className="size-4" /></span><h2 className="font-semibold">Transaction volume</h2></div><p className="mt-2 text-sm text-muted-foreground">Payment activity over the last 30 days</p></div><button className="rounded-lg border border-border bg-background px-3 py-2 text-xs font-medium transition-colors hover:bg-accent hover:text-accent-foreground">Last 30 days⌄</button></div><div className="mt-5 grid grid-cols-2 gap-4 sm:flex sm:gap-8"><div><p className="text-xs text-muted-foreground">Deposits</p><p className="mt-1 text-lg font-semibold">$482,650 <span className="text-xs font-medium text-emerald-700 dark:text-emerald-300">↗ 12.8%</span></p></div><div><p className="text-xs text-muted-foreground">Withdrawals</p><p className="mt-1 text-lg font-semibold">$294,280 <span className="text-xs font-medium text-emerald-700 dark:text-emerald-300">↗ 8.2%</span></p></div></div><div className="mt-3 h-[250px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={volumeSeries} margin={{ top: 12, right: 4, left: -22, bottom: 0 }}><defs><linearGradient id="depositFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.24} /><stop offset="95%" stopColor="var(--primary)" stopOpacity={0} /></linearGradient><linearGradient id="withdrawalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#398895" stopOpacity={0.19} /><stop offset="95%" stopColor="#398895" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="4 5" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} dy={10} /><Tooltip contentStyle={{ borderRadius: 12, borderColor: "var(--border)", background: "var(--card)", color: "var(--foreground)" }} /><Area type="monotone" dataKey="deposits" stroke="var(--primary)" strokeWidth={2.5} activeDot={{ r: 4, strokeWidth: 0 }} fill="url(#depositFill)" /><Area type="monotone" dataKey="withdrawals" stroke="#398895" strokeWidth={2.5} activeDot={{ r: 4, strokeWidth: 0 }} fill="url(#withdrawalFill)" /></AreaChart></ResponsiveContainer></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Requests overview</h2><p className="mt-1 text-sm text-muted-foreground">Current queue status</p></div><button className="text-sm font-medium text-primary">View all</button></div><div className="mt-7 flex items-center gap-5"><div className="relative grid size-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#f59e0b 0 ${pendingStop}%, #10b981 ${pendingStop}% ${approvedStop}%, #f43f5e ${approvedStop}% 100%)` }}><div className="grid size-24 place-items-center rounded-full bg-card text-center"><span><strong className="block text-2xl">{data.length}</strong><span className="text-[10px] text-muted-foreground">Total requests</span></span></div></div><div className="space-y-3 text-sm"><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-amber-500" />Pending <strong className="ml-auto">{pending.length}</strong></p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-500" />Approved <strong className="ml-auto">{data.filter((row) => row.status === "approved").length}</strong></p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-rose-500" />Rejected <strong className="ml-auto">{data.filter((row) => row.status === "rejected").length}</strong></p></div></div><div className="mt-7 rounded-xl bg-muted/50 p-4"><p className="text-xs font-medium">Average processing time</p><p className="mt-1 text-xl font-semibold">18 <span className="text-sm font-normal text-muted-foreground">minutes</span></p><p className="mt-1 text-xs text-emerald-600">↓ 6 min faster this week</p></div></section>
    </div>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">Recent transactions</h2><p className="mt-1 text-sm text-muted-foreground">Latest activity from across your accounts</p></div><button className="text-sm font-medium text-primary">See all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-muted/40 text-[11px] uppercase tracking-wider text-muted-foreground"><tr>{["Transaction", "Client", "Date", "Amount", "Status"].map((label) => <th key={label} className="px-5 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{recent.map((row) => <tr key={row.id}><td className="px-5 py-4 font-medium">{row.id}<span className="ml-2 text-xs font-normal capitalize text-muted-foreground">{row.kind}</span></td><td className="px-5 py-4">{row.clientName}</td><td className="px-5 py-4 text-muted-foreground">{new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(row.createdAt))}</td><td className="px-5 py-4 font-semibold">{currency(row.amount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${row.status === "pending" ? "bg-amber-500/10 text-amber-700" : row.status === "approved" ? "bg-emerald-500/10 text-emerald-700" : "bg-rose-500/10 text-rose-700"}`}>{row.status}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
