"use client";

import { useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Check, Clock3, MoreHorizontal, Search, X } from "lucide-react";
import { useRequests, useUpdateRequest } from "@/lib/queries/requests";
import type { RequestKind, RequestStatus } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const money = (amount: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);
const date = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const statusStyle: Record<RequestStatus, string> = { pending: "bg-amber-500/10 text-amber-700 dark:text-amber-400", approved: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400", rejected: "bg-rose-500/10 text-rose-700 dark:text-rose-400" };
const accountNumbers: Record<string, string> = { "BA-01": "•••• 4821", "BA-02": "•••• 1904", "BA-03": "•••• 7365", "BA-04": "•••• 6312", "BA-05": "•••• 0948" };

export function RequestsTable({ kind }: { kind: RequestKind }) {
  const { data = [], isLoading } = useRequests(kind);
  const mutation = useUpdateRequest();
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const rows = useMemo(() => data.filter((row) => (filter === "all" || row.status === filter) && `${row.id} ${row.clientName} ${row.reference}`.toLowerCase().includes(search.toLowerCase())), [data, filter, search]);
  const Icon = kind === "deposit" ? ArrowDownToLine : ArrowUpFromLine;
  return <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{kind === "deposit" ? "Deposit requests" : "Withdrawal requests"}</h2><p className="mt-1 text-sm text-muted-foreground">Review and process incoming {kind === "deposit" ? "funding" : "payout"} requests.</p></div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search requests…" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div>
    <div className="flex gap-1 border-b border-border px-5 py-3">{["all", "pending", "approved", "rejected"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-1.5 text-xs font-medium capitalize ${filter === item ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}>{item}{item === "pending" ? ` · ${data.filter((row) => row.status === "pending").length}` : ""}</button>)}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted/40 text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Request</th><th className="px-5 py-3 font-medium">Client</th><th className="px-5 py-3 font-medium">Amount</th>{kind === "withdrawal" && <th className="px-5 py-3 font-medium">Payout account</th>}<th className="px-5 py-3 font-medium">Submitted</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Action</th></tr></thead><tbody className="divide-y divide-border">{isLoading ? <tr><td colSpan={7} className="px-5 py-12 text-center text-muted-foreground">Loading requests…</td></tr> : rows.map((row) => <tr key={row.id} className="transition-colors hover:bg-muted/25"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-muted text-primary"><Icon className="size-4" /></span><span><span className="block font-medium">{row.id}</span><span className="text-xs text-muted-foreground">{row.reference}</span></span></div></td><td className="px-5 py-4"><span className="block font-medium">{row.clientName}</span><span className="text-xs text-muted-foreground">{row.clientId}</span></td><td className="px-5 py-4 font-semibold">{money(row.amount, row.currency)}</td>{kind === "withdrawal" && <td className="px-5 py-4 text-muted-foreground">{row.bankAccountId ? accountNumbers[row.bankAccountId] ?? "Verified account" : "Verified account"}</td>}<td className="px-5 py-4 text-muted-foreground">{date(row.createdAt)}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium capitalize ${statusStyle[row.status]}`}>{row.status === "pending" ? <Clock3 className="size-3" /> : row.status === "approved" ? <Check className="size-3" /> : <X className="size-3" />}{row.status}</span></td><td className="px-5 py-4">{row.status === "pending" ? <div className="flex items-center gap-2"><Button size="sm" className="h-8" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: row.id, status: "approved" })}>Approve</Button><Button variant="outline" size="sm" className="h-8" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: row.id, status: "rejected" })}>Reject</Button></div> : <Button size="icon" variant="ghost" aria-label="More options"><MoreHorizontal className="size-4" /></Button>}</td></tr>)}{!isLoading && rows.length === 0 && <tr><td colSpan={7} className="px-5 py-14 text-center"><p className="font-medium">No matching requests</p><p className="mt-1 text-sm text-muted-foreground">Try another search or status filter.</p></td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between border-t border-border px-5 py-3 text-xs text-muted-foreground"><span>Showing {rows.length} of {data.length} requests</span><span>Updated just now</span></div></section>;
}
